---
title: "Grupo de estudos de aprendizagem em R/ Data Science com R — UFBA"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 
Enoch Filho et. al.  
+ 20-maio-2020  
+ (atualizado em 2020-05-20)  



## Instruções e Preparativos  

Este repositório está no github: [gpee-aprendizagem-em-R](https://github.com/enoches/gpee_aprendizagem-em-R)  

Os avisos estão no [Gloogle Classroom](https://classroom.google.com/u/0/c/ODc0OTI1MjUxOTZa)  



### Para quem for baixar o programa no computador: 

- Instalar ou atualizar o R mais recente (https://cran.rstudio.com/bin/windows/base/)  
- Instalar ou atualizar o RStudio mais recente (https://rstudio.com/products/rstudio/download/)  
- Instalar os programas do script `instalar-pacotes.R`  

Obs: caso já tenha o R + RStudio instalados, sugiro atualizar tudo, inclusive os pacotes já instalados.  



### Para quem for usar diretamente na internet, sem instalar:  

- Criar uma conta gratuita no RStudio Cloud (https://rstudio.cloud/)   
- Entrar neste projeto: (https://rstudio.cloud/project/1291558)  
- Clicar em "Save a permanent copy"  





## Ordem dos scrips utilizados    

Para rever o ritmo dos encontros desde o início, pode seguir os scripts abaixo, na ordem:

1. `instalar-pacotes.R`  
1. `encontro-03.R`  
1. `encontro-05.R`  
1. `encontro-07.Rmd`  
1. `lista_01_dataviz.R`  
1. `lista_01_dataviz_gabarito.R`   
1. `aula1_Fabio_copia-editada.r`    
1. `exemploDeJoin_Fabio.r`    
1. `aed_monociclos.R`